### PR TITLE
FUSETOOLS-2455 - fixing issue with global DF wizard hang

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by bfitzpat** [comment]
testPR

**Comment by lhein** [comment]
for me it now freezes my UI every time I add a new dataformat which needs a download of libs

**Comment by bfitzpat** [comment]
Yeah, apparently this doesn't actually fix the issue. Back to the drawing board. But I can't reproduce it on my end, so I'm open to suggestions. :)

**Comment by apupier** [comment]
proposal to fix it in another PR: https://github.com/jbosstools/jbosstools-fuse/pull/1066

**Pull request closed without merging**
