### PR TITLE
FUSEDOC-2122 Updates in help plugin for better consistency in use of …

### PR DESCRIPTION
**Pull request by TovaCohen**
…terms. Third try.

I think this looks better. Fingers crossed.

### CODE REVIEW

**Comment by TovaCohen** [comment]
Yay! 
What's the DCO failing check? Do I need to do something?

**Comment by bfitzpat** [comment]
All commits now require a sign-off from the committer for legal reasons. There is now a check on github pull requests. To activate the signed-off automatically in your commit message you can set a preference: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit

You may need to update your commit after setting the preference.

**Comment by bfitzpat** [comment]
@TovaCohen This approval is brand new this week so I'm still figuring it out myself. 

If you have the Git tooling installed in your Eclipse installation (Oxygen), you should find it at: Help->Preferences, Team->Git->Committing and then just check the "Footers - Insert Signed-off-by" box

It appears you can do the same thing with "git commit --signoff" and then you might need to to a "git push -f TovaCohen FUSEDOC-2122-3"

But this is uncharted territory for me. @nickboldt any words of wisdom?

**Comment by nickboldt** [comment]
You can amend the commit message and push in the relevant signoff info, then force-push the updated PR to your topic branch. The signoff is just text. If you use the --signoff flag  it adds it for you automatically.

For example, here's a commit I did earlier today w/ a signoff in it: https://github.com/jbdevstudio/jbdevstudio-product/commit/7d567a6245876d66440c69ddb5dd3307b8aac508

If you want to amend the commit comment by hand [1], just add a line like this:

Signed-off-by: TovaCohen <your@email.address.here>

[1] https://github.com/github/hub/issues/198#issuecomment-147059582

**Comment by TovaCohen** [comment]
I was able to amend the commit message to add the signoff, but now my topic branch is out of sync with something and I can't get the pull right. Can anyone help me with this:

[tcohen@tcohen jbosstools-fuse]$ git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> FUSEDOC-2122-3

[tcohen@tcohen jbosstools-fuse]$ git pull origin master
From https://github.com/TovaCohen/jbosstools-fuse
 * branch            master     -> FETCH_HEAD
Already up-to-date.
[tcohen@tcohen jbosstools-fuse]$ git push origin FUSEDOC-2122-3
Username for 'https://github.com': TovaCohen
Password for 'https://TovaCohen@github.com': 
To https://github.com/TovaCohen/jbosstools-fuse.git
 ! [rejected]        FUSEDOC-2122-3 -> FUSEDOC-2122-3 (non-fast-forward)
error: failed to push some refs to 'https://github.com/TovaCohen/jbosstools-fuse.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[tcohen@tcohen jbosstools-fuse]$ ^C
[tcohen@tcohen jbosstools-fuse]$

**Comment by apupier** [comment]
you need to use `git push --force`

**Pull request merged**
