### PR TITLE
FUSETOOLS-3185 - Avoid 0.9.0 which is introducing regression

### PR DESCRIPTION
**Pull request by apupier**
when a new version without regression will be available, we will just
need to move to this new version

https://issues.jboss.org/browse/JBIDE-26563 needs to be fixed before this PR can build (and so be merged)

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
> This will disable the plugin only, right?

it means that we must have a org.sonatype.tycho.m2e with a version between 0.8.1 and 0.9.0.
In case, both versions are provided, the behavior needs to be checked.

**Comment by lhein** [comment]
I just meant that when we only have 0.9.x in the TP our plugin will not resolve any more and be disabled.

**Comment by apupier** [comment]
> In case, both versions are provided, the behavior needs to be checked.

if both provided, the MANIFEST.MF is generated so it is fine.

**Comment by apupier** [comment]
> I just meant that when we only have 0.9.x in the TP our plugin will not resolve any more and be disabled.

no, the build is breaking. And you won't be able to install it

**Comment by lhein** [comment]
ok, that is at least a stable behaviour.

**Comment by apupier** [comment]
blocked by https://github.com/jbosstools/jbosstools-build/pull/287

**Pull request merged**
