### PR TITLE
Fusetools 2395 fixlayout for edit several jmx routes

### PR DESCRIPTION
**Pull request by apupier**
I think a UI test will be more relevant, what do you think?

This PR can wait for the master to be moved 10.x

### CODE REVIEW

**Comment by lhein** [comment]
but we are in code freeze, just a reminder

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
created https://issues.jboss.org/browse/JBTIS-1135 for UI test

**Pull request merged**
