### PR TITLE
FUSETOOLS-3372 - use generic editor for xml support

### PR DESCRIPTION
**Pull request by apupier**
- avoid usage of WTP xml editor which is hardly maintained and which has
problem to support Java 11 as source code level
- more Camel Language Server features are available
- requires to use Filters instead of "input" types for section filtering
- it is using internal API but this internal API is already used by M2e
and I opened an issue to have an official API:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567627

Screenshot from 2020-10-06 11-19-41

### CODE REVIEW

**Comment by apupier** [comment]
test in error is:

```
org.eclipse.reddeer.core.exception.CoreLayerException: Item to does not exist in table
	at org.jboss.tools.fuse.ui.bot.tests.CamelEditorTest.testCodeCompletion(CamelEditorTest.java:253)
```

the code in CamelEditorTest is:

`assistent.chooseProposal("to");`

looking at the code in org.eclipse.reddeer.jface.text.contentassist.ContentAssistant.chooseProposal(String):
```
	public void chooseProposal(String proposal){
		log.debug("Choose content assist proposal - "+proposal);
		TableItemHandler.getInstance().setDefaultSelection(contentAssistTable.getItem(proposal).getSWTWidget());
		new WaitWhile(new ShellIsAvailable(this));
	}
```

my guess is that the ContentAssistant is not dealing with asynchronuous completion.
There is several seconds where there is only "computed proposals"

computedProposalForCompletion

so it sounds like RedDeer is not supporting the Generic Text Editor completely.
@djelinek have I understood well?

nota: subsequent calls are fast so a workaround can be to fall completion a first time without checking content or use a conditional wait using assistent.getProposals()

**Comment by djelinek** [comment]
HI @apupier sorry for late response I lost notification in my inbox :( 

it really looks like problem with caching proposals for first invocation of content assistant.

@odockal do you know something more about RedDeer support for the Generic Text Editor please?

**Comment by djelinek** [comment]
@apupier if it can wait will Monday I can try to reproduce failures on my local and provide some better waiting condition which can help until it will be fixed on RedDeer side which next release is planned on December.

**Comment by lhein** [comment]
@djelinek any progress on this issue yet?

**Comment by apupier** [comment]
> any progress on this issue yet?

fix done in reddeer and part of Reddeer latest milestone. Asked to include it in Target Platform: https://issues.redhat.com/browse/FUSETOOLS-3380?focusedCommentId=15530667&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15530667

**Comment by djelinek** [comment]
Honestly for now I don't know if I can do something more.. if I can, just let me know please, from discussion on slack about including RedDeer latest milestone I am not sure what are next planned steps..

**Comment by apupier** [comment]
using new Reddeer, tests are now passing.

I'm balanced to merge it before code of AM1 to let time to potential users to test it more. or we take the time to test it more internally manually (by engineering and QE).

@lhein @djelinek any thoughts?

**Review by bfitzpat — APPROVED** [review]

**Comment by djelinek** [comment]
In theory I am not strictly against BUT.. 
- How much this change affects Fuse Tooling users? I suppose it will a lot if it is XML editor changes and that is used on common basis in Fuse Tooling...

- Do we really want to release this "untested" with AM1 and let users to test and provide potential fixes immediately in upcoming GA release (13th Jan) or we would like to keep Fuse Tooling healthy, skip this one in AM1 and test it as most as possible and release inside GA?

- In theory if we will incorporate this PR into AM1 release and all ENG JUnit tests will pass and all QE UI tests will pass in QE testing frame, everything should be fine, BUT we need to be aware that if there will be found some issues related to these changes it will be possibly considered as Blockers and we will need to consider respin or postponing of AM1 release

**Comment by apupier** [comment]
ok, will not include in AM1.

**Pull request merged**
