### PR TITLE
FUSETOOLS-2457: Create UI test for Bean support in Configurations tab

### PR DESCRIPTION
**Pull request by apodhrad**
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
ok, I tried manually and it reveals a real bug, the Finish button is enabled although Class and Factory bean are both undefined

image

**Comment by apodhrad** [comment]
yes, I'm going to raise an issue for that

**Comment by apupier** [comment]
I provided a fix with this PR: https://github.com/apodhrad/jbosstools-fuse/pull/6

**Comment by apodhrad** [comment]
I merged the fix and the PR is ready

**Comment by apupier** [comment]
testPR

**Pull request merged**
