### PR TITLE
FUSETOOLS-3351 - upgrade minimal requirements to Java 11 in all bundles

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Review by bfitzpat — COMMENTED** [review]
Are Eclipse builds still broken?

**Comment by apupier** [comment]
> Are Eclipse builds still broken?

In general, the Eclipse build is not broken.
This PR is not working due to indirect dependencies https://issues.redhat.com/browse/FUSETOOLS-3351?focusedCommentId=15618950&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15618950 but there is good chance that upstream will be fixed soon: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566183 it has started to bubble up from root issue

**Comment by zregvart** [comment]
retest this please

**Review by djelinek — APPROVED** [review]

**Comment by apupier** [comment]
error on CI (that i do not reproduce locally):
```
15:56:05 [ERROR] Cannot resolve project dependencies:
15:56:05 [ERROR]   Software being installed: org.fusesource.ide.updatesite raw:11.10.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):11.10.0-SNAPSHOT
15:56:05 [ERROR]   Missing requirement: org.jboss.tools.fuse.ui.bot.tests 11.10.0.qualifier requires 'osgi.bundle; org.fusesource.ide.catalogs 11.0.0' but it could not be found
15:56:05 [ERROR]   Cannot satisfy dependency: org.fusesource.ide.updatesite raw:11.10.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):11.10.0-SNAPSHOT depends on: org.eclipse.equinox.p2.iu; org.jboss.tools.fuse.ui.bot.tests 0.0.0
```

**Pull request closed without merging**
