### PR TITLE
FUSETOOLS-3329 - updating configuration for latest Fuse 7.6 release

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [X] Did you use the Jira Issue number in the commit comments?
- [X] Did you set meaningful commit comments on each commit?
- [X] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [X] Are all Sonar reported issues fixed or can they be ignored?
- [X] Is there no duplicated code?
- [X] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [X] Have you used the correct file header copyright comment?
- [X] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
added the Syndesis version mapping and updated the readme to make it easier to find the information for future releases.

**Comment by lhein** [comment]
updated the IgniteVersionMapper

**Comment by apupier** [comment]
rebasing on master should fix the failing tests

**Comment by apupier** [comment]
rebased

**Comment by apupier** [comment]
@lhein this is ready for merge. Remember to NOT delete the branch after merge and provide the PR to switch the branch to master

**Comment by apupier** [comment]
> provide the PR to switch the branch to master

done https://github.com/jbosstools/jbosstools-fuse/pull/1609

**Pull request merged**
