### PR TITLE
FUSETOOLS-2879 - filter runtime in "New Runtime" wizard

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [x] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
for Karaf:
image
for wildly/EAP:
image
for comparison without filter (as it is currently):
image
image


we can notice that several runtimes not Fuse/Karaf/Wildfly/EAP are still appearing but it seems a bug to me. What do you think? @robstryker

**Comment by apupier** [comment]
@lhein @bfitzpat having the list hardcoded makes it easier to see which versions we are supporting and is a bit faster, on the other hand when a new runtime is added, we will need to update this list. Do you have another argument to choose between one those 2 solutions? (we can also start like that and modify in a next iteration)

**Comment by lhein** [comment]
doesn't it work with org.jboss.ide.eclipse.as.runtime.* also? I would prefer if we can make it more dynamic

**Comment by apupier** [comment]
> doesn't it work with org.jboss.ide.eclipse.as.runtime.* also? I would prefer if we can make it more dynamic

no it doesn't work

**Comment by lhein** [comment]
Then I fear I don't understand what the alternative approach to hard coding would be here?

**Comment by apupier** [comment]
> Then I fear I don't understand what the alternative approach to hard coding would be here?

Retrieve all runtimes from our code and filter the list based on ids and the kind of pattern that you mentioned.

**Comment by lhein** [comment]
Actually the later approach is easier to maintain and I would opt for the dynamic approach.

**Comment by robstryker** [comment]
The weird ones still being shown aren't server adapters. They are references to extensions that can be installed. I imagine an API enhancement could be made here to not show those.

**Comment by apupier** [comment]
> The weird ones still being shown aren't server adapters. They are references to extensions that can be installed. I imagine an API enhancement could be made here to not show those.

thanks for the answer. I opened the enhancement request: https://issues.jboss.org/browse/JBIDE-25920

**Comment by apupier** [comment]
> Actually the later approach is easier to maintain and I would opt for the dynamic approach.

updated with dynamic approach.
Maybe some old Wildfly/EAP versions can be filtered out? If yes, we can raise another JIRA enhancement request.

**Pull request merged**
