### PR TITLE
FUSETOOLS-2898 - addressing scroll bars

### PR DESCRIPTION
**Pull request by bfitzpat**
- fixed for REST element list
- added scrollable section for REST operations list

Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by bfitzpat** [comment]
Had to recreate this branch with some weird rebase issues, but now should have scroll bars working in the REST element list as well as the REST operations list

**Comment by bfitzpat** [comment]
Nothing was needed for the REST Elements list btw - it worked out of the box with a long enough list of REST elements. But it did take a little doing to get the Operations list to scroll.

**Comment by bfitzpat** [comment]
Still looks like we have some weirdness going on with one of the Camel model plug-ins
`21:09:01 [INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
21:09:01 [ERROR] Cannot resolve project dependencies:
21:09:01 [ERROR]   Software being installed: org.fusesource.ide.camel.validation.tests.integration 11.1.0.qualifier
21:09:01 [ERROR]   Missing requirement: org.fusesource.ide.camel.editor.tests.integration 11.1.0.qualifier requires 'osgi.bundle; org.fusesource.ide.camel.model.service.impl.v2170redhat630343 11.0.0' but it could not be found
21:09:01 [ERROR]   Cannot satisfy dependency: org.fusesource.ide.camel.validation.tests.integration 11.1.0.qualifier depends on: osgi.bundle; org.fusesource.ide.camel.editor.tests.integration 0.0.0
21:09:01 [ERROR] 
21:09:01 [ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
21:09:01 [ERROR] Cannot resolve dependencies of MavenProject: org.fusesource.ide.core:org.fusesource.ide.camel.validation.tests.integration:11.1.0-SNAPSHOT @ /home/jenkins/workspace/jbosstools-fuse_PullRequest/core/tests/org.fusesource.ide.camel.validation.tests.integration/pom.xml: See log for details -> [Help 1]`

**Comment by bfitzpat** [comment]
Looks like there's some jenkins issues:
`16:56:16 Starting xvnc
16:56:16 [jbosstools-fuse_PullRequest] $ vncserver :26 -localhost -nolisten tcp
16:56:16 FATAL: Cannot run program "vncserver" (in directory "/home/jenkins/workspace/jbosstools-fuse_PullRequest"): error=2, No such file or directory
16:56:16 java.io.IOException: error=2, No such file or directory
16:56:16 	at java.lang.UNIXProcess.forkAndExec(Native Method)
16:56:16 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
16:56:16 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
16:56:16 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
16:56:16 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to fuse-jenkins-308
16:56:16 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
16:56:16 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
16:56:16 		at hudson.remoting.Channel.call(Channel.java:908)
16:56:16 		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1053)
16:56:16 		at hudson.Launcher$ProcStarter.start(Launcher.java:450)
16:56:16 		at hudson.plugins.xvnc.Xvnc.doSetUp(Xvnc.java:130)
16:56:16 		at hudson.plugins.xvnc.Xvnc.setUp(Xvnc.java:96)
16:56:16 		at jenkins.tasks.SimpleBuildWrapper.setUp(SimpleBuildWrapper.java:146)
16:56:16 		at hudson.model.Build$BuildExecution.doRun(Build.java:157)
16:56:16 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
16:56:16 		at hudson.model.Run.execute(Run.java:1724)
16:56:16 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:56:16 		at hudson.model.ResourceController.execute(ResourceController.java:97)
16:56:16 		at hudson.model.Executor.run(Executor.java:429)
16:56:16 Caused: java.io.IOException: Cannot run program "vncserver" (in directory "/home/jenkins/workspace/jbosstools-fuse_PullRequest"): error=2, No such file or directory
16:56:16 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
16:56:16 	at hudson.Proc$LocalProc.<init>(Proc.java:249)
16:56:16 	at hudson.Proc$LocalProc.<init>(Proc.java:218)
16:56:16 	at hudson.Launcher$LocalLauncher.launch(Launcher.java:930)
16:56:16 	at hudson.Launcher$ProcStarter.start(Launcher.java:450)
16:56:16 	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1299)
16:56:16 	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1260)
16:56:16 	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
16:56:16 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
16:56:16 	at hudson.remoting.Request$2.run(Request.java:358)
16:56:16 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
16:56:16 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:56:16 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:56:16 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:56:16 	at java.lang.Thread.run(Thread.java:748)`

**Comment by bfitzpat** [comment]
testPR

**Comment by apupier** [comment]
another build error:
08:10:44 Gdk-Message: SWT: Fatal IO error 11 (Resource temporarily unavailable) on X server :95.

relaunched...

**Comment by bfitzpat** [comment]
The scrolled composite in this case contains ALL of the custom SWT work for each of the operations. It was the logical container to scroll and works as designed. But I'm not sure that's the question you're asking?

**Comment by apupier** [comment]
> The scrolled composite in this case contains ALL of the custom SWT work for each of the operations. It was the logical container to scroll and works as designed. But I'm not sure that's the question you're asking?

it was what i'm asking. i didn't remember that we are using a non-standard widgets

**Comment by bfitzpat** [comment]
Once https://github.com/jbosstools/jbosstools-fuse/pull/1426 is merged, I can trigger a resize event once the operations are created.

**Comment by bfitzpat** [comment]
@apupier I'm not quite seeing what you're seeing with this issue - can you record a video by chance to more clearly illustrate what's going on?

**Comment by bfitzpat** [comment]
Figured out a solution to the inconsistent resizing of the scroll bar. See if that works better for you now @apupier ?

**Comment by apupier** [comment]
> Figured out a solution to the inconsistent resizing of the scroll bar. See if that works better for you now @apupier ?

works better!

**Comment by bfitzpat** [comment]
Woo hoo!

**Pull request merged**
