### PR TITLE
FUSETOOLS-1915 - fixed problem with multi-project deletion and opened…

### PR DESCRIPTION
**Pull request by lhein**
… editors

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [x] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
This is not the original error. But its bad that you still see the issue. On linux the issue is gone when testing. My strategy was to first close all open invalid editors which are not activated so they don't get focused and hence trigger the memento logic and then finally close the active and focused invalid editor. Somehow that doesn't seem to work on windows?

**Comment by lhein** [comment]
@apupier can u retest. I can't reproduce and I was actually able to reproduce what u saw above after some testing. Now its gone and its working.

**Comment by lhein** [comment]
templates job fails with unrelated errors.

`Error Message

Expecting empty but was:<[{"severity"=1, "resource affected"="/home/jenkins/workspace/jbosstools-fuse_PullRequest-OnlyTemplates/editor/tests/org.fusesource.ide.projecttemplates.tests.integration/target/work sp@cé/FuseIntegrationProjectCreatorRunnableForSimpleIT-SimpleJavaProject-2.21.0.000033-fuse-000001-redhat-1", "message"="build.properties does not exist", "compilerKey"="compilers.p.build", "type: "="org.eclipse.pde.core.problem", "Creation time: "=1522781026853L}]>

Stacktrace

java.lang.AssertionError: 
Expecting empty but was:<[{"severity"=1, "resource affected"="/home/jenkins/workspace/jbosstools-fuse_PullRequest-OnlyTemplates/editor/tests/org.fusesource.ide.projecttemplates.tests.integration/target/work sp@cé/FuseIntegrationProjectCreatorRunnableForSimpleIT-SimpleJavaProject-2.21.0.000033-fuse-000001-redhat-1", "message"="build.properties does not exist", "compilerKey"="compilers.p.build", "type: "="org.eclipse.pde.core.problem", "Creation time: "=1522781026853L}]>
	at org.fusesource.ide.camel.tests.util.AbstractProjectCreatorRunnableIT.checkNoValidationIssueOfType(AbstractProjectCreatorRunnableIT.java:146)
	at org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableIT.checkNoValidationWarning(FuseIntegrationProjectCreatorRunnableIT.java:183)
	at org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableIT.testProjectCreation(FuseIntegrationProjectCreatorRunnableIT.java:130)
	at org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableForSimpleIT.testEmptyJavaProjectCreation(FuseIntegrationProjectCreatorRunnableForSimpleIT.java:74)
`

**Comment by apupier** [comment]
I still have the same error https://github.com/orgs/jbosstools/teams/fuse-tooling-eng

**Comment by apupier** [comment]
closing outdated PR

**Pull request closed without merging**
