### PR TITLE
FUSETOOLS-3186 - Use cached JSON ObjectReader

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
before
image

after
image

with 3 different camel version used in the workspace, we are going from 2300ms to 400ms (5.75 times faster!)

**Comment by bfitzpat** [comment]
The time savings is impressive!

**Comment by apupier** [comment]
> Obviously there's an issue with a test build somewhere?

I think it is due to flaky test. I relaunched

> But is there ever a case where we need to reset the language reader? Or are we at most only loading the catalog a single time during a session with no way to re-load the catalog without shutting down the IDE and restarting it?

The Object Reader which is cached is for a specific metamodel. We are providing a single one for each of the Component, DataFormat, Language, EIP.
The same metamodel is used to load any versions of the Camel Catalog. No need to restart the IDE.
The day, the metamodel used to load the Camel catalog won't be backward compatible, we will have to generate different metamodel classes (Component, DataFormat, Language, EIP) but as we put the ObjectReader inside the classes, a new ObjectReader will be available quite naturally.

**Comment by apupier** [comment]
For information (and if you can notice others spot for improvements), reusing the same ObjectReader for the metamodel class is recommended in the wiki of the library: https://github.com/FasterXML/jackson-docs/wiki/Presentation:-Jackson-Performance#basics-things-you-should-do-anyway

**Pull request merged**
