### PR TITLE
FUSETOOLS-1915 - works around potential NPE during project deletion

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by bfitzpat** [comment]
test PR

**Comment by bfitzpat** [comment]
testPR

**Comment by apupier** [comment]
with the current state of the PR it is even worse.
After closing, reopening Fuse Tooling a single time, the editor is not displayed:
image

**Comment by bfitzpat** [comment]
Ok. Obviously I don't have a handle on this one again, so closing and will look again down the line. Sorry for the trouble.

**Pull request closed without merging**
