### PR TITLE
JBIDE-25139 remove some spaces to test PR...

### PR DESCRIPTION
**Pull request by nickboldt**
JBIDE-25139 remove some spaces to test PR builder

Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
retest this please

**Comment by lhein** [comment]
testPR

**Comment by nickboldt** [comment]
testPR

**Comment by lhein** [comment]
@nickboldt do we need that one still? If not then please close it.

**Pull request closed without merging**
