### PR TITLE
FUSETOOLS-2729 - switched from pom configured values to json configured values and fixed a bug in template selection

### PR DESCRIPTION
**Pull request by lhein**
# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [x] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
based on #1292

**Comment by lhein** [comment]
base for #1295

**Comment by apupier** [comment]
in the title "and fixed a bug in template selection", doesn't make sense to put the part of the commit that deal with that in a previous PR?

**Comment by apupier** [comment]
"switched from pom configured values to json configured values" as discussed by chat, what is the way used upstream? Will they change to this way too? If not, shouldn't we stay with that and make them change the json schema?

**Pull request closed without merging**
