### PR TITLE
Fusetools 2567 improve filtering of methods available

### PR DESCRIPTION
**Pull request by apupier**
# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [x] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
@apodhrad Can you check that I understood (and implemented) the correct functional behavior please?

**Comment by apodhrad** [comment]
Two more restrictions should be added
* non-void methods
* non-constructors

Note: the above restrictions are not covered by UI tests

**Comment by apodhrad** [comment]
I can extend the UI tests and send you PR which you can add to this PR, wdyt?

**Comment by apodhrad** [comment]
https://github.com/apupier/jbosstools-fuse/pull/9

**Comment by apodhrad** [comment]
testPR

**Pull request merged**
