### PR TITLE
Fusetools 3189 java11 compatibility2 attempt with all in same bundle

### PR DESCRIPTION
**Pull request by apupier**
# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
https://github.com/jbosstools/jbosstools-fuse/pull/1511 to be reviewed and merged before

**Comment by apupier** [comment]
wsdl2rest tests passed with Java 11 job https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Fuse%20Tooling/job/jbosstools-fuse_master-jdk11/lastCompletedBuild/testReport/

**Comment by apupier** [comment]
created https://issues.jboss.org/browse/FUSETOOLS-3194 for follow-up, improving design to help for future maintenance

**Comment by djelinek** [comment]
UI tests with java 8 seems to be ok

**Pull request merged**
