### PR TITLE
FUSETOOLS-2405 - updating AMQ Blueprint template

### PR DESCRIPTION
**Pull request by bfitzpat**

### CODE REVIEW

**Comment by lhein** [comment]
testPR

**Comment by bfitzpat** [comment]
I did not test with 2.18.x - just the 2.17.x version it was on.  @apodhrad Any chance we can test on 2.18?

**Comment by apodhrad** [comment]
@bfitzpat The version 2.18 can be tested with FIS but I do not have big experiences with FIS so I suggest to wait for @tsedmik and we can together try it on Monday.

**Comment by apupier** [comment]
this cannot be tested with a local camel context?

**Comment by apodhrad** [comment]
By testing it locally with 2.18.1.redhat-000015 I'm getting the following error
```
Failed to create route file-to-jms-route at: >>> To[activemq:incomingOrders] <<< in route: Route(file-to-jms-route)[[From[file:work/in]] -> [Log[Receiv... because of Failed to resolve endpoint: activemq://incomingOrders due to: Password must also be provided when using username/password as credentials.
```

**Comment by apodhrad** [comment]
Note that I had to remove the version of activemq-camel from
```
    <dependency>
      <groupId>org.apache.activemq</groupId>
      <artifactId>activemq-camel</artifactId>
      <version>5.11.0.redhat-000015</version>
    </dependency>
```
so that the project could be built

**Comment by bfitzpat** [comment]
Going to close this and start over with some different ideas with the next release.

**Pull request closed without merging**
