### PR TITLE
FUSETOOLS-2401 - Revert class introducing regression for cancel not

### PR DESCRIPTION
**Pull request by apupier**
working

regression introduced by:
https://github.com/jbosstools/jbosstools-fuse/commit/bf39873f2c44a50e4ab8f59f8401d78235caf477

# Pull Request Checklist

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Function

- [ ] Does the project still build fine locally?
- [ ] Does your modification work?
- [ ] Is the non-happy path working, too?
- [ ] Are other parts that use the same component still working fine?

## Code Style

- [ ] Are method-/class-/variable-names meaningful?
- [ ] Are methods concise, not too long?
- [ ] Are catch blocks catching precise Exceptions only (no catch all)?
- [ ] Have you used the correct file header copyright comment?
- [ ] Have you set the correct year in the headers of new files?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

### CODE REVIEW

**Comment by apupier** [comment]
@tsedmik do you have automated test checking for cancellation when there are unknown Camel version? (As you caught it, to know if it was a manual test or an automated one and see how much I should try to write one)

**Comment by tsedmik** [comment]
There is no automated test for this scenario yet. I raised an issue to create it - see https://issues.jboss.org/browse/FUSETOOLS-2735.

**Comment by apupier** [comment]
I managed to be in previous state and in fact we can't cancel 2 times a verify (unless the Thread launched in background has finished)
I need to check that it was really already behaving like that before.

**Comment by apupier** [comment]
I will create another PR moving forward instead of reverting as the issue was more common only when there was outage fo several maven repositories

**Pull request closed without merging**
