### PR TITLE
FUSETOOLS-2886 - support all rest elements in editor

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
meant as an alternative approach to 
https://github.com/jbosstools/jbosstools-fuse/pull/1314

**Comment by lhein** [comment]
Thanks for raising the test jira. I will wait for @bfitzpat to review this PR and give his ok too.

**Comment by bfitzpat** [comment]
We definitely get some interesting things in the list when we pull in the "rest" world from the catalog:
* rest
* responseHeader
* rests (?? what's this?)
* restBinding (not part of the REST DSL)
* verb 
* delete
* put
* patch
* head
* post
* param
* restConfiguration
* restProperty
* get
* options
* responseMessage
* restContext
* restContextRef

I think for the READ ONLY case, this is a good start - but I'm very curious about some of these elements.

**Comment by lhein** [comment]
testPR

**Comment by bfitzpat** [comment]
thanks @lhein !

**Pull request merged**
