### PR TITLE
Fusetools 3207 workaround for java12

### PR DESCRIPTION
**Pull request by apupier**
to be reviewed first https://github.com/jbosstools/jbosstools-fuse/pull/1519

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
EAP test are still failing on CI but I cannot reproduce locally, either manually or by launching tests

**Comment by apupier** [comment]
EAP templates now fixed with JDK 12. The failures are other ones:


org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.testCXFCodeFirstJavaProjectCreation[2.22.0] | 35 sec | 1
-- | -- | --
org.jboss.tools.fuse.transformation.editor.internal.util.ImportExportPackageUpdaterForManifestIT.testExportPackageNotAddedForExternalClasses | 4.2 sec | 2

**Comment by bfitzpat** [comment]
Are we fixing the other template failures in a separate PR or including them in this one?

**Comment by apupier** [comment]
> Are we fixing the other template failures in a separate PR or including them in this one?

another PR, I created 2 other issues:
https://issues.jboss.org/browse/FUSETOOLS-3223
https://issues.jboss.org/browse/FUSETOOLS-3224

**Pull request merged**
