### PR TITLE
FUSETOOLS-2772 - upgrade ignite version to 1.2.3

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
@apupier here is the PR to upgrade to 1.2.3 ignite version

**Comment by apupier** [comment]
still same question than here https://github.com/jbosstools/jbosstools-fuse/pull/1238#discussion_r162873185
Where can we found the list of versions for Tech preview 3?
there is also 1.2.6 version for instance.

**Comment by lhein** [comment]
@rhuss told me that 1.2.3 is the version for TP3. I have no idea if the maintain an official document about versions.

**Comment by apupier** [comment]
the list is available here https://docs.google.com/spreadsheets/d/1ohR6poCaYmQ7Ga3OWgSd189sT8MlXexDCZbmb_SY994/edit#gid=0

so it means that the version planned t be used is the upstream version and not the productized version. Is it fine?

**Comment by lhein** [comment]
Interesting...it is the first time I hear from a productized version.

**Comment by lhein** [comment]
ok, seems we need to update the PR to use version 1.2.3.fuse-000001 instead. Will do that asap.

**Comment by lhein** [comment]
done

**Comment by apupier** [comment]
I had in mind to put the Tech preview 3 version. Having the .fuse version will require users to have access to staging repositories. Are they public for Fuse 7 already? Are they configured by default?

**Comment by apupier** [comment]
I think that the PR needs to be rebased to be succesful Only qualifier changed for (org.fusesource.ide.syndesis.extension.core/10.2.0.v20180129-1346). Expected to have bigger x.y.z than what is available in baseline (10.2.0.v20180117-2222)

**Comment by lhein** [comment]
rebased

**Comment by apupier** [comment]
the failure seems to be due tto the fact that the test is relying on the online version available on master

**Comment by lhein** [comment]
of course it does. so I guess we can't expect this PR to build successfully this way.

**Comment by apupier** [comment]
All other tests are passing.
I tested manually through the wizard that it is working with 1.2.3.
I launched the test with forcing usage of 1.2.3 version fro Syndesis and it is working.

This fix should fix the last known master failure.

This issue is currently impacting end users on Fuse Tooling 10.2.0

I started to look to modify the code but with minimal changes, it will mean stopping to test the behavior that users will have (as we won't rely on the online version that they use)

Given that I think that we should merge this PR.

**Pull request merged**
