### PR TITLE
FUSETOOLS-2846 - support Fuse 7.0 TP3

### PR DESCRIPTION
**Pull request by apupier**
- add the value in dropdown-list by default
- modify templates to use a different early access repository then it
was previously deployed
- improve code to get the fabric8-maven-plugin version from provided
values instead of latest online one.

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [x] Are there unit-tests?
- [x] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
current state as draft but would like to see what is the current status of failing tests to paralellize with local environment

**Comment by apupier** [comment]
job failures due to

> 03:01:26.949 [ERROR]    Unknown Host: http://download.jboss.org/jbosstools/oxygen/staging/updates/core/4.5.3.AM2/plugins/org.fusesource.ide.jmx.activemq.source_10.3.0.v20180125-1522.jar: Unknown host download.jboss.org

**Comment by apupier** [comment]
reproduced failing test locally due to a concurrency issue (working always with breakpoints and sometimes working)

**Comment by apupier** [comment]
this time it is another test which has failed SyndesisExtensionProjectCreatorRunnableForSimpleIT.testSimpleExtensionProjectCreation
so all failures due to unstable product/test :(

**Comment by apupier** [comment]
testPR

**Comment by lhein** [comment]
bildschirmfoto von 2018-03-13 14-57-07

**Comment by lhein** [comment]
Unable to test this PR further as the above issue blocks me.

**Comment by apupier** [comment]
> I have staging repos enabled. Maybe the right repo is not amongst the defined ones? Shouldn't it be added automatically or do we expect users to know that URI and enter it themselves?

I think the verify button is not using the staging repositories.
The creation should work when not using the verify", I can include an improvement for the verify button

**Comment by lhein** [comment]
The verify logic should really use staging repos if enabled. I'd consider this a bug in existing logic.

**Comment by apupier** [comment]
Camel catalog is available on https://maven.repository.redhat.com/earlyaccess/all/org/apache/camel/camel-catalog/2.21.0.000033-fuse-000001-redhat-1/
https://maven.repository.redhat.com/earlyaccess/all is part of staging repositories:
image

and seems that the staging repositories are used to check for  this version:
https://github.com/jbosstools/jbosstools-fuse/blob/1387af561a406bef458f24e86d1b3d44d4bc95b0/core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelMavenUtils.java#L259-L262
image

I remove .m2/repository/org/apache/camel/camel-core and .m2/repository/org/apache/camel/camel-catalog and then try the verify button and it is working.

@lhein do you have more precise error in logs?

**Comment by cunningt** [comment]
testPR

**Comment by apupier** [comment]
the build failed with

> java.lang.reflect.InvocationTargetException: null
> 	at org.fusesource.ide.syndesis.extensions.ui.templates.BasicSyndesisExtensionXmlProjectTemplate.getConfigurator(BasicSyndesisExtensionXmlProjectTemplate.java:34)
> 	at org.fusesource.ide.projecttemplates.adopters.AbstractProjectTemplate.create(AbstractProjectTemplate.java:60)
> 	at org.fusesource.ide.projecttemplates.util.BasicProjectCreatorRunnable.run(BasicProjectCreatorRunnable.java:86)
> 	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
> 	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
> 	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:483)
> 	at org.fusesource.ide.syndesis.extensions.tests.integration.wizards.SyndesisExtensionProjectCreatorRunnableIT.testProjectCreation(SyndesisExtensionProjectCreatorRunnableIT.java:115)
> 	at org.fusesource.ide.syndesis.extensions.tests.integration.wizards.SyndesisExtensionProjectCreatorRunnableForSimpleIT.testSimpleExtensionProjectCreation(SyndesisExtensionProjectCreatorRunnableForSimpleIT.java:19)

but cannot reproduce locally

**Comment by bfitzpat** [comment]
Even with staging repositories enabled, I'm seeing this:
```
WARN: Cannot load version 2.21.0.000033-fuse-000001-redhat-1 due Error grabbing Grapes -- [unresolved dependency: org.apache.camel#camel-catalog;2.21.0.000033-fuse-000001-redhat-1: java.util.ConcurrentModificationException at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907)]Mar 15, 2018 11:42:49 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server repo.fusesource.com failed to respond
Mar 15, 2018 11:42:49 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Mar 15, 2018 11:42:52 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server repo.fusesource.com failed to respond
Mar 15, 2018 11:42:52 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Mar 15, 2018 11:43:05 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server repo.fusesource.com failed to respond
Mar 15, 2018 11:43:05 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Mar 15, 2018 11:43:43 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (org.apache.commons.httpclient.NoHttpResponseException) caught when processing request: The server repo.fusesource.com failed to respond
Mar 15, 2018 11:43:43 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
```

**Comment by bfitzpat** [comment]
I get the same results when attempting to create a new Fuse Integration Project and verify the new version.

**Comment by apupier** [comment]
> To clarify - this is the Configure->Change Camel Versions approach with an existing project.

The change camel version is not looking for staging repositories or configured repositories of the project, it is an existing issue. I discovered it while writing the test and created an enhancement request: https://issues.jboss.org/browse/FUSETOOLS-2865

As the version is provided in the combo and not added by user, do you think that it is required to implement it in the PR?

**Comment by apupier** [comment]
> It spins for a LOOOONG time... in fact I had to kill it on both dialogs after 10-15 minutes of waiting.

the fact that it is taking a long time might be due to the usage of Ivy/groovy.
https://issues.jboss.org/browse/FUSETOOLS-2505
https://issues.jboss.org/browse/FUSETOOLS-2489
And the fact that you needed to kill it (because the stop didn't answer) is a bug in Ivy which is not listening to thread interruption https://issues.apache.org/jira/browse/IVY-1572

**Comment by apupier** [comment]
>> To clarify - this is the Configure->Change Camel Versions approach with an existing project.
> 
> The change camel version is not looking for staging repositories or configured repositories of the project, it is an existing issue. I discovered it while writing the test and created an enhancement request: https://issues.jboss.org/browse/FUSETOOLS-2865
> 
> As the version is provided in the combo and not added by user, do you think that it is required to implement it in the PR?

after starting investigation, in fact the staging repositories are looked up, "just" not the one defined in the project.
there are also 3 repositories which were always added for the lookup, I added the Red Hat Early access one which will do the trick for Tech Previews

**Comment by apupier** [comment]
I reproduce the test failure when running from maven command-line, not from Eclipse

**Comment by apupier** [comment]
> I reproduce the test failure when running from maven command-line, not from Eclipse

fixed with commit: https://github.com/jbosstools/jbosstools-fuse/pull/1297/commits/72315c1d47013dd3806f557c6d2859825303062b

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
failed test is:

```
java.lang.AssertionError: 
Expecting:
 <false>
to be equal to:
 <true>
but was not.
	at org.fusesource.ide.launcher.tests.integration.remote.debug.ProjectWithDebugAvailableDeployedHelper.launchCamelRoute(ProjectWithDebugAvailableDeployedHelper.java:154)
	at org.fusesource.ide.launcher.tests.integration.remote.debug.ProjectWithDebugAvailableDeployedHelper.start(ProjectWithDebugAvailableDeployedHelper.java:82)
	at org.fusesource.ide.launcher.tests.integration.remote.debug.AbstractRemoteCamelLaunchConfigurationDelegate.setup(AbstractRemoteCamelLaunchConfigurationDelegate.java:49)
	at org.fusesource.ide.launcher.tests.integration.remote.debug.RemoteCamelLaunchConfigurationDelegateOverJolokiaIT.setup(RemoteCamelLaunchConfigurationDelegateOverJolokiaIT.java:59)
```

**Comment by lhein** [comment]
Aurelien, I am wondering why its needed to add the repo to each template? wouldn'T it be easier to add it to the staging repo preference automatically?

**Comment by apupier** [comment]
> Aurelien, I am wondering why its needed to add the repo to each template? wouldn'T it be easier to add it to the staging repo preference automatically?

the Early access repository is not a staging repository. It is where the artefacts for Tech Previews are provided publicly.
So to have a template working out of the box, the early access repositories need to be added to the template.

**Comment by lhein** [comment]
I am just unsure where the difference is to a staging repo. I mean those tech preview repos are kind of similar.

**Comment by apupier** [comment]
> I am just unsure where the difference is to a staging repo. I mean those tech preview repos are kind of similar.

staging repository:
- artefacts can be removed at any time
- targeting very advanced users

The tech previews repository will last at least several months (if not years after they are on the early access repository)
By having them inside the pom.xml it avoids to have users that will try a Fuse 7 Tech Preview version and have a not working template.

**Comment by lhein** [comment]
I am not really convinced that it needs a different treatment than the staging repos but I guess thats fine as is.

**Pull request merged**
