### PR TITLE
FUSETOOLS-2899 - provide online configuration for camel version to

### PR DESCRIPTION
**Pull request by apupier**
select by default

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
this PR allows to modify after release the default Camel version which will be selected by default in dropdowns.
I tried to keep it minimal.
I'm reusing the mechanism in place with properties file. It will allow to reuse this same file for other default version such as Syndesis version (worth implementing it also? even if we didn't finally talked about it during meeting yesterday; it can be done in a separate PR anyway)

The drawbacks of current implementation is as explained during meeting that for instance when Fuse 7.X will be released, we will change the version and previous Fuse Tooling, such as Fuse Tooling 10.3.0, will be affected too. We have no guarantee that it will work well but it is the way acknowledged to go initially.
For Fuse Tooling 10.4.0, i think that we should implement a way to separate per version this config files, in this case, this current implementation is enough for 10.3.0.

**Comment by apupier** [comment]
failures due to CI KO as missing xvnc https://pastebin.com/uNHjZS8Z

**Comment by zregvart** [comment]
retest this please

**Comment by lhein** [comment]
looks good for a first iteration and can be used for syndesis too.

**Pull request merged**
