### PR TITLE
JBIDE-27598: refactor tests to do not rely anymore on locus

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Review by lhein — DISMISSED** [review]
lgtm

**Review by apupier — COMMENTED** [review]
What's the reason for embedding lib? This is a bad practice in OSGi world often cause troubles.

**Comment by sbouchet** [comment]
> What's the reason for embedding lib? This is a bad practice in OSGi world often cause troubles.

we're removing completely our locus update site for providing maven artifacts as OSGI bundles. our goal is to use the new PDE/M2E feature that aloww to use directly any maven artifact in a Target platform. (https://github.com/eclipse-m2e/m2e-core/blob/master/RELEASE_NOTES.md#1182) that is bundled with AM1. 
looking at the current situation, this is only a workaround for the integration test to pass. 
the goal is then to move ALL embedded libs to TP and then be able to manage everything in one place ( and be able to update easily any deps. )

**Comment by apupier** [comment]
> the goal is then to move ALL embedded libs to TP and then be able to manage everything in one place ( and be able to update easily any deps. )

Why not moving first the embedded libs to TP?
if not possible, can you point which issue will track it to be sure that this will be done for this lib?

**Comment by sbouchet** [comment]
our TP deployment process does not handle this new feature yet and this might take quite some time.
moving this one in libs will also permit to get rid of locus jaxb. 
marking as draft as I'll be off for the next weeks.

**Comment by sbouchet** [comment]
ongoing work for updating TP to hadle maven repos still on hold. please review to get rid of locus for good.

**Comment by apupier** [comment]
>> if not possible, can you point which issue will track it to be sure that this will be done for this lib?

> our TP deployment process does not handle this new feature yet and this might take quite some time.

I created https://issues.redhat.com/browse/JBIDE-28361

Merge is currently blocked as main branch was broken. Awaiting finish of rebuild of Target platform and then a rebuild of the main branch

**Pull request merged**
