### PR TITLE
FUSETOOLS-3333 - avoid NPE with UpdatevalueStrategy

### PR DESCRIPTION
**Pull request by apupier**
new version of Target Platform doesn't allow anymore to use
UpdateValueStrategy.create(Converter) with a null value.

also specify generic types for better readability

blind push awaiting local target Platform build but at least it will start build of PRs in case it is enough

### CODE REVIEW

**Comment by lhein** [comment]
changes look good. lets see what Jenkins says :)

**Comment by apupier** [comment]
> lets see what Jenkins says :)

it won't tell that much, only no regression on other parts of the software. As Fuse Online tests are deactivated https://issues.redhat.com/browse/FUSETOOLS-3249

**Comment by apupier** [comment]
> blind push awaiting local target Platform build

Target Platform rebuilt, I reproduce the NPE with master, and it is working fine with the PR

**Comment by apupier** [comment]
the PR job for template will have 5 failing tests unrelated to this issue, see https://issues.redhat.com/browse/FUSETOOLS-3332

**Comment by apupier** [comment]
the remaining [failing tests](https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbosstools-fuse_PullRequest-OnlyTemplates/1086/) will be covered by https://github.com/jbosstools/jbosstools-fuse/pull/1603

**Comment by apupier** [comment]
@lhein @bfitzpat please review

**Pull request merged**
