### PR TITLE
Updating additional TP changes

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by bfitzpat** [comment]
I don't think this quite works either - I'm seeing missing plug-ins in the generated TP locally - specifically

image

But though I can get it to run, it definitely is throwing some funky errors in the debugging instance.

**Comment by lhein** [comment]
@apupier can you review the PR? Just go into targetplatform folder and execute 

  mvn clean verify -Pmultiple2repo -Dmirror-target-to-repo.includeSources=true

**Comment by apupier** [comment]
> @apupier can you review the PR? Just go into targetplatform folder and execute
> 
> mvn clean verify -Pmultiple2repo -Dmirror-target-to-repo.includeSources=true

I don't really see the interest. The versioning is changing on each modification in JBoss Tools plugins. Changes are interesting only when there are different plugins required

**Comment by bfitzpat** [comment]
From my point of view, having a working TP is essential -- so that's my interest. I wonder if there are any ways to automate this process and have it triggered when the upstream TP gets bumped?

**Comment by apupier** [comment]
> I wonder if there are any ways to automate this process and have it triggered when the upstream TP gets bumped?

it is possible but it will involve commits in the history for each new build of JBoss Tools components that we are declaring in the TP. It has not been done when we migrated to JBoss Tools.

**Comment by bfitzpat** [comment]
Closing this as we seem to simply be regenerating the TP locally by hand these days rather than keeping anything up to date in the git repo.

**Pull request closed without merging**
