### PR TITLE
FUSETOOLS-2682: Add support for Fuse 6.2.1.R9

### PR DESCRIPTION
**Pull request by apodhrad**
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
isn't "Add support for Fuse 6.2.1R9 "instead of "Add support for Fuse 6.3.0.R5" ?

**Comment by apodhrad** [comment]
You are right. I have already fixed it.

**Comment by apodhrad** [comment]
Tests are failing due to missing Camel artifacts in Maven Central repo and also in RedHat GA repo, please see https://issues.jboss.org/browse/ENTESB-7475

**Comment by apupier** [comment]
I rebased to see which tests are failing (and be the more up to date possible ^^)

**Comment by apupier** [comment]
The test are failing just because the online version of the bom mapping file is not up-to-date on the master branch.
Everything is fine then. just our PR is not handling well enough not already updated bom mapping files

**Pull request merged**
