### PR TITLE
FUSETOOLS-3321 - move sonar properties in pom

### PR DESCRIPTION
**Pull request by apupier**
to workaround regression of Sonar with "default" organization.

note: modified Sonar job to be able to test the Sonar push, see https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Fuse%20Tooling/job/jbosstools-fuse.sonar_master/367 build

### CODE REVIEW

**Comment by apupier** [comment]
not working:

```
11:15:18 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project project: Project 'fusetools' can't have 2 modules with the following key: fusetools -> [Help 1]
11:15:18 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project project: Project 'fusetools' can't have 2 modules with the following key: fusetools
```

**Comment by lhein** [comment]
So the suggested workaround does not work?

**Comment by apupier** [comment]
> So the suggested workaround does not work?

seems not, I have not checked what is happening

**Comment by lhein** [comment]
If it doesn't fix the issue we can close this PR?

**Pull request closed without merging**
