### PR TITLE
FUSETOOLS-3471 - add Fuse 7.9 release

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
2 failures:
- one timeout https://studio-jenkins-csb-codeready.apps.ocp4.prod.psi.redhat.com/job/Studio/job/Engineering/job/pr_checks/job/pullrequest-fuse/43/console , good chance because it requires the bundle cached, see https://github.com/jbosstools/jbosstools-fuse/pull/1702
- FuseIntegrationProjectCreatorRunnableForOSESringBootIT.testOSESpringBootProjectCreation[2.23.2.fuse-790054-redhat-00001] test failing, good chance that it needs to use a more up-to-date example, see https://github.com/jbosstools/jbosstools-fuse/pull/1684

**Pull request merged**
