### PR TITLE
FUSETOOLS-3386 - upgrade wsdl2rest to 7.8 fuse artifacts

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Review by bfitzpat — DISMISSED** [review]

**Comment by apupier** [comment]
working locally with last version. Now PR jobs blocked by Ci that has been shutdowned

**Comment by apupier** [comment]
testPR

**Comment by zregvart** [comment]
testPR

**Comment by zregvart** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
> working locally with last version. Now PR jobs blocked by Ci that has been shutdowned

No more working locally (and CI PR failure confirm that). I think I didn't regenerated lib folder when i tried. Same problem then reported previously https://github.com/jbosstools/jbosstools-fuse/pull/1638#event-4130008734

**Comment by apupier** [comment]
working now with a workaround.

Given that:
 - between cxf 3.2.7 and 3.3.6, the default values are no more the same
for the Template Resource Loader
 - our bundle is embedding libs and have a dependency on
org.eclipse.m2e.maven.runtime that exports a different version of
Velocity (1.5. although cxf expects 1.7)

I set back default values for Template Resource Loader compatible with
Velocity 1.5

**Review by lhein — APPROVED** [review]

**Pull request merged**
