### PR TITLE
Fusetools 1696 provide specific validation for containers not expressed in xsd

### PR DESCRIPTION
**Pull request by apupier**
recommend to review (and merge)  https://github.com/jbosstools/jbosstools-fuse/pull/1045 before reviewing this PR to better see what is related to this PR more precisely

### CODE REVIEW

**Comment by apupier** [comment]
example on choice, validation on Diagram and on Source:
image
image

**Comment by apupier** [comment]
testPR

**Comment by bfitzpat** [comment]
This one still seems unable to merge due to some conflicts.

**Comment by bfitzpat** [comment]
testPR

**Comment by bfitzpat** [comment]
Ok, so all the PR builds have been successful, but it appears we still need to rebase this one?

**Comment by lhein** [comment]
Don't see any problem with this PR. All builds fine. Merged it.

**Pull request merged**
