### PR TITLE
JBDS-4706 rename JBDS to Red Hat Developer...

### PR DESCRIPTION
**Pull request by nickboldt**
JBDS-4706 rename JBDS to Red Hat Developer Studio

Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
@nickboldt if I understood well, the test will pass when all Jboss Tools project would have been updated and available when building Fuse Tooling, right?
Do you know which project we should monitor to relaunch the build?

**Comment by nickboldt** [comment]
Why do these string changes depend on JBT projects being updated and built?

**Comment by apupier** [comment]
> Why do these string changes depend on JBT projects being updated and built?

the test is going through a dialog having the JBT name in the title. I guess there is no specific jboss tools red deer dialog for it. @tsedmik Can you check please? is it worthy contribute it if not?

**Comment by tsedmik** [comment]
@apupier yes, as far as I know, there is no such dialog implementation in RedDeer.

**Pull request merged**
