### PR TITLE
mf-fusedoc-2708 help plugin files for 11.1

### PR DESCRIPTION
**Pull request by MelissaFlinn**
Signed-off-by: Melissa Flinn <mflinn@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by bfitzpat** [comment]
Except for the image size issues that @tsedmik already told @MelissaFlinn about, these changes look great. The context Ids we needed added are in there and I was able to verify using the latest changes to https://github.com/jbosstools/jbosstools-fuse/pull/1476 that we see what is expected for selected global beans, endpoints, and data formats.

**Comment by lhein** [comment]
this PR needs to be rebased with Master to reflect the latest changes. Otherwise the fix for log component, addition to global config doc etc are invisible within this PR and therefore complicated to test.

**Comment by lhein** [comment]
PR seems good otherwise.

**Comment by apupier** [comment]
> this PR needs to be rebased with Master to reflect the latest changes. Otherwise the fix for log component, addition to global config doc etc are invisible within this PR and therefore complicated to test.

rebased

**Pull request merged**
