### PR TITLE
FUSETOOLS-2785 - use right version of log4j-over-slf4j in

### PR DESCRIPTION
**Pull request by apupier**
build.properties

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by lhein** [comment]
IMO that can be done in #1253

**Comment by apupier** [comment]
> IMO that can be done in #1253

it can.
I preferred to separate the commit to ease Code Review.

**Comment by lhein** [comment]
yeah, but thats exactly what is broken in #1253

**Comment by apupier** [comment]
incorporated in this other PR https://github.com/jbosstools/jbosstools-fuse/pull/1253

**Pull request closed without merging**
