### PR TITLE
FUSETOOLS-2405 - updating spring AMQ template readme

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
@tsedmik or @apupier any idea where these quickstarts came from because they're not at https://github.com/apache/camel/tree/master/examples

**Comment by apupier** [comment]
I searched a bit on internet but cannot found a similar one so it might have been completely created for Tooling (strange)

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Pull request merged**
