### PR TITLE
FUSETOOLS-3446 - workaround to external issue of missing xsds

### PR DESCRIPTION
**Pull request by apupier**
see https://github.com/EclipseFdn/osgi.org/issues/11

### CODE REVIEW

**Review by bfitzpat — APPROVED** [review]
Should we put in a TODO or some comment to remind us to revert this at some point when we have a better fix?

**Comment by apupier** [comment]
> Should we put in a TODO or some comment to remind us to revert this at some point when we have a better fix?

absolutely https://issues.redhat.com/browse/FUSETOOLS-3447 :-)

**Comment by bjhargrave** [comment]
I have added the redirect from www.osgi.org to the xsd home on docs.osgi.org. So you probably don't need this work around any more.

**Comment by apupier** [comment]
> I have added the redirect from [www.osgi.org](http://www.osgi.org) to the xsd home on docs.osgi.org. So you probably don't need this work around any more.

unfortunately, this is not working. it seems that Eclipse Lemminx is unable to follow the redirection.

**Comment by apupier** [comment]
> > I have added the redirect from [www.osgi.org](http://www.osgi.org) to the xsd home on docs.osgi.org. So you probably don't need this work around any more.
> 
> unfortunately, this is not working. it seems that Eclipse Lemminx is unable to follow the redirection.

rectification. it has failed one time in 10 tries (but the first one)

**Comment by apupier** [comment]
> > > I have added the redirect from [www.osgi.org](http://www.osgi.org) to the xsd home on docs.osgi.org. So you probably don't need this work around any more.
> > 
> > 
> > unfortunately, this is not working. it seems that Eclipse Lemminx is unable to follow the redirection.
> 
> rectification. it has failed one time in 10 tries (but the first one) locally.

I cannot reproduce anymore and it wasn't reporduced on CI so I guess I di d a bad manipulation initially.

**Pull request closed without merging**
