### PR TITLE
FUSETOOLS-2964 - fix data transformation for Fuse 7.0+

### PR DESCRIPTION
**Pull request by apupier**
import package needs to be provided only for Fuse 6.3+ and 7.0-

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
spotted a bug in old code making the added code useless (it wqs looking for Maven plugins instead of Maven dependencies to find org.apache.camel:camel-core artefact...)
more complicated than just what initially done anyway as some packages needs to be added on export package and it is not responding to same criterium

**Comment by tsedmik** [comment]
@apupier automated tests are not ready yet ... I raise an issue for it - https://issues.jboss.org/browse/FUSETOOLS-2987. You can track the progress there.

**Comment by tsedmik** [comment]
@apupier I tested your changes locally and they works! Tested with JBoss Fuse 6.3.0 R8 and Red Hat Fuse 7.0.0 GA.

**Comment by apupier** [comment]
the test in failure on CI are due to unrelated change to this PR, they should be fixed with: https://github.com/jbosstools/jbosstools-fuse/pull/1364

**Pull request merged**
