### PR TITLE
FUSETOOLS-2940 - Ensure users don't think runtime selection is mandatory

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [x] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
image

**Comment by MelissaFlinn** [comment]
(1) I recommend instead changing the "Choose the runtime environment" heading text to:
**Choose the runtime environment (optional)**

(2) If you do (1), I recommend that you remove the (optional) in each selection list. Actually, I find having it there to be confusing. Also, remove uppercase R in "Runtime". In summary, change "No Runtime pre-selected (optional)" to:
**No runtime pre-selected**

**Comment by apupier** [comment]
> (1) I recommend instead changing the "Choose the runtime environment" heading text to:
> Choose the runtime environment (optional)
> 
> (2) If you do (1), I recommend that you remove the (optional) in each selection list. Actually, I find having it there to be confusing. Also, remove uppercase R in "Runtime". In summary, change "No Runtime pre-selected (optional)" to:
> No runtime pre-selected

choosing the Runtime environment type is mandatory, it is only to choose a specific runtime in the combo which is optional

**Comment by MelissaFlinn** [comment]
OK. Thanks for clearing up my misunderstanding.

**Comment by MelissaFlinn** [comment]
optionalruntimesuggestion

What do you think about this suggestion?

**Comment by apupier** [comment]
@MelissaFlinn I prefer to have it compacted on the same line. (sorry :s) Your proposal makes repeating "Runtime" 2 times on the same line.

I know that Lars doesn't like my proposed sentence "No Runtime pre-selected (optional)".

Will need to think a bit more about it, hope night will provide good advice (or someone else ^^)

**Comment by MelissaFlinn** [comment]
@apupier No worries. I'd suggest to avoid the double use of Runtime, change the option in the selection to "None selected" so that it is:

o Karaf/Fuse on Karaf
   Runtime (optional): None selected v
o Wildfly/Fuse on EAP
  Runtime (optional): None selected v

**Comment by apupier** [comment]
with proposal from Melissa:
image

**Pull request merged**
