### PR TITLE
FUSETOOLS-2885 - Improve texts in New Fuse Integration wizard

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [x] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [x] Are there unit-tests?
- [x] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
result of updated text (and a little the layout):
image
image

**Comment by apupier** [comment]
@MelissaFlinn Please review to check that I modified it correctly and if you are catching more things to change based on this new proposal.

**Comment by MelissaFlinn** [comment]
Thank you...here are a few minor changes:
Page 2 
- change "Choose **your** deployment platform" to "Choose **the** deployment platform"
- change "**Specify** the runtime environment" to "**Choose** the runtime environment"

Page 3
- change "Select a template **to use to set up** your new project" to "Select a template **for** your new project"
- change "**The** list of templates..." to "**This** list of templates...."
- in the "Where can you find more examples?" link - should it be:  "Where can you find more **templates**?" or at least: "Where can you find more examples **to use as templates**?"

**Comment by apupier** [comment]
image
image
image

**Comment by lhein** [comment]
@tsedmik @apodhrad QE approval required

**Pull request merged**
