### PR TITLE
FUSEDOC-2122 Last updates for help plugin for 10.0. Signed-off by: To…

### PR DESCRIPTION
**Pull request by TovaCohen**
…vaCohen tcohen@redhat.com

Mostly, these updates improve the consistency for how we use terms in the doc, such as tab, editor, view, perspective, pane, panel and so on. There are other updates for conciseness and clarity. But there is one update that needs to get into the 10.0 help plugin. This update changes a link to the Integration Stack installation guide to be a link to the Developer Studio installation guide. So hopefully, this will build and merge smoothly.  "Allow edits from maintainers." is checked.

### CODE REVIEW

**Comment by apupier** [comment]
I updated the signed-off, it needs to match the "author" name so TovaCohen --> Tova Cohen

**Comment by apupier** [comment]
why this PR has been closed????

**Comment by apupier** [comment]
as i don't hav ethe rights to reopen this PR, i created another one: https://github.com/jbosstools/jbosstools-fuse/pull/1040 from my github fork repo

**Comment by lhein** [comment]
It looks like you closed the PR, Aurelien.

Am 31.07.2017 8:29 vorm. schrieb "Aurélien Pupier" <notifications@github.com

**Pull request closed without merging**
