### PR TITLE
FUSETOOLS-2907 - Provide more precise Bom Mapping for manually entered

### PR DESCRIPTION
**Pull request by apupier**
Camel Version

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [x] Is the non-happy path working, too?

## Maintainability

- [x] Are all Sonar reported issues fixed or can they be ignored?
- [x] Is there no duplicated code?
- [x] Are method-/class-/variable-names meaningful?

## Tests

- [x] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [x] Have you used the correct file header copyright comment?
- [x] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
testPR

**Comment by bfitzpat** [comment]
Test looks out of whack with what you're doing in the utility... 
* 2.17.x was Fuse 6.2.1 BOM in the utility
* but you're testing 2.15.1 with the 6.2.1 BOM and 2.17.0 with the 6.3.0 BOM

What am I missing?

**Comment by apupier** [comment]
> Test looks out of whack with what you're doing in the utility...
> 
> 2.17.x was Fuse 6.2.1 BOM in the utility

no, it is: "when strictly inferior to 2.17.0, then use 6.2.1 BOM"

> but you're testing 2.15.1 with the 6.2.1 BOM and 2.17.0 with the 6.3.0 BOM

and the test helps to understand the expected behavior

**Comment by bfitzpat** [comment]
Gotcha. I was looking at it backwards. Thanks

**Pull request merged**
