### PR TITLE
FUSETOOLS-2132 - Provide more Trace for Validation and Markers

### PR DESCRIPTION
**Pull request by apupier**
to help investigate intermittent failures on CI

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by bfitzpat** [comment]
Why disable validation during project creation? Is the validation interrupting the process?

**Comment by apupier** [comment]
> Why disable validation during project creation? Is the validation interrupting the process?

The validation is not interrupting the process.
The validation is launched several times on the same files as we are modifying the project. We just need to validate when we have finished to modify the project.
It will also avoid to have concurrent validation running which might cause the xsd validation error (perhaps, no proof, just a guess)

**Comment by bfitzpat** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
That PR doesn't build any more.

**Comment by lhein** [comment]
Needs to be rebased correctly.

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
@apupier how about rebase and merge?

**Comment by apupier** [comment]
> @apupier how about rebase and merge?

I will rebase asap but I would wait to merge because the patched code is adding too much technical debt and for no it has not been provided needed information when the test is failing. need to find more trace/exception to log before a useful merge

**Comment by apupier** [comment]
the initial issue has not occurred for several weeks so closing this PR

**Pull request closed without merging**
