### PR TITLE
updated the target platform to allow build with sources

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by lhein** [comment]
failed because of OSE test failure unrelated to this PR

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
I tried to build it locally but I have several errors: 
image
I will try again after a clean

**Comment by lhein** [comment]
What I did:
cd targetplatform
mvn clean verify -Pmultiple2repo -Dmirror-target-to-repo.includeSources=true

**Comment by apupier** [comment]
after clean and rebuild, it is working fine, seems that it doesn't like when there is no clean (but it means a loooot of time to recreate it)

**Pull request merged**
