### PR TITLE
bump up to parent pom version = 4.24.0.Final-SNAPSHOT

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by apupier** [comment]
testPR

**Comment by sbouchet** [comment]
tried different thing, still looking around why those tests are failling.

**Comment by sbouchet** [comment]
Ignored the failing tests for now, aproved by @apupier for the release

**Comment by sbouchet** [comment]
testPR

**Comment by apupier** [comment]
I will merge despite Pull Request Template job is still failing. It is known flaky tests for several years (just usually less flaky). The failing tests were not the same between the various builds, so they all passes at least one time.

**Pull request merged**
