### PR TITLE
FUSETOOLS-2557 - make camel version loading fallback messages warning…

### PR DESCRIPTION
**Pull request by lhein**
… instead of error

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by lhein** [comment]
I agree, but that can be done in a separate PR/issue. I raised https://issues.jboss.org/browse/FUSETOOLS-2557 to track it.

**Comment by apupier** [comment]
> I agree, but that can be done in a separate PR/issue. I raised https://issues.jboss.org/browse/FUSETOOLS-2557 to track it.

I think that we should keep the same issue at it was reported from AERI. if we close it, users will be notified that the issue is solved which is not the case. or maybe the related issue can be updated in AERI

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by lhein** [comment]
Change to FUSETOOLS-2557 and make this Jira just for the LogLevel change

**Comment by lhein** [comment]
closing in favor of #1139

**Pull request closed without merging**
