### PR TITLE
FUSETOOLS-2550: UI Tests - Preference pages - referencedComposite can't be null

### PR DESCRIPTION
**Pull request by tsedmik**
https://issues.jboss.org/browse/FUSETOOLS-2550

Signed-off-by: Tomáš Sedmík <tsedmik@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
Shouldn't we remove the contructor ConsolePreferencePage() ? it will force to be in correct state, isn't it?
There are several other XXXPreferencePage which are following the same pattern, should we do the same for them?

**Comment by tsedmik** [comment]
@apupier yes, you are right. I'll look at it again.

**Comment by tsedmik** [comment]
@apupier done

**Comment by apupier** [comment]
seems that you missed FuseServerRuntimePreferencePage

**Comment by tsedmik** [comment]
Good catch. Thank you. _FuseServerRuntimePreferencePage_ is fixed.

**Comment by apupier** [comment]
@apodhrad can you review this PR please as you better know this part of code?

**Pull request merged**
